#!/bin/bash
set -euo pipefail

# LocalMem × Codex CLI 一键集成 / One-click integration for OpenAI Codex CLI (Linux/macOS)
# Usage: curl -fsSL https://raw.githubusercontent.com/MemoryGet/LocalMem/main/integrations/codex/install.sh | bash

REPO="MemoryGet/LocalMem"
INSTALL_DIR="$HOME/.iclude"
BIN_DIR="$INSTALL_DIR/bin"

# ── 颜色输出 / Color output ──
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; exit 1; }

# ── 检测平台 / Detect platform ──
detect_platform() {
    OS=$(uname -s | tr '[:upper:]' '[:lower:]')
    ARCH=$(uname -m)
    case "$ARCH" in
        x86_64)  ARCH="amd64" ;;
        aarch64) ARCH="arm64" ;;
        arm64)   ARCH="arm64" ;;
        *)       error "Unsupported architecture: $ARCH" ;;
    esac
    case "$OS" in
        linux|darwin) ;;
        *)  error "Unsupported OS: $OS. Use install.ps1 for Windows." ;;
    esac
    info "Platform: ${OS}/${ARCH}"
}

# ── 获取最新版本 / Get latest release version ──
get_latest_version() {
    VERSION=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" 2>/dev/null \
        | grep '"tag_name"' | head -1 | sed -E 's/.*"([^"]+)".*/\1/' || true)
    if [ -z "$VERSION" ]; then
        VERSION="latest"
        warn "Could not detect latest release version"
    fi
    info "Version: ${VERSION}"
}

# ── 下载二进制 / Download binaries ──
download_binaries() {
    mkdir -p "$BIN_DIR"
    local base_url="https://github.com/${REPO}/releases/download/${VERSION}"

    for bin in iclude-mcp iclude-cli; do
        local url="${base_url}/${bin}-${OS}-${ARCH}"
        local dest="${BIN_DIR}/${bin}"
        info "Downloading ${bin}..."
        if ! curl -fsSL -o "$dest" "$url"; then
            error "Failed to download ${bin} from ${url}"
        fi
        chmod +x "$dest"
    done
    info "Binaries installed to ${BIN_DIR}/"
}

# ── 加入 PATH / Add to PATH ──
add_to_path() {
    local path_line="export PATH=\"${BIN_DIR}:\$PATH\""
    local added=false

    for rc in "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.profile"; do
        if [ -f "$rc" ]; then
            if ! grep -q ".iclude/bin" "$rc" 2>/dev/null; then
                echo "" >> "$rc"
                echo "# LocalMem memory system" >> "$rc"
                echo "$path_line" >> "$rc"
                added=true
            fi
        fi
    done

    export PATH="${BIN_DIR}:$PATH"

    if [ "$added" = true ]; then
        info "Added ${BIN_DIR} to PATH (restart shell or run: source ~/.bashrc)"
    else
        info "PATH already configured"
    fi
}

# ── 生成配置 / Generate config ──
generate_config() {
    local config_file="$INSTALL_DIR/config.yaml"

    if [ -f "$config_file" ]; then
        warn "Config already exists at ${config_file}, skipping"
        return
    fi

    local api_key=""
    if [ -t 0 ]; then
        echo ""
        echo -n "Enter your OpenAI API Key (or press Enter to skip): "
        read -r api_key
    fi

    if [ -z "$api_key" ]; then
        api_key='${OPENAI_API_KEY}'
        warn "No API key provided. Set OPENAI_API_KEY environment variable before use."
    fi

    cat > "$config_file" << YAML
# LocalMem config — auto-generated by install.sh
storage:
  sqlite:
    enabled: true
    path: "${INSTALL_DIR}/iclude.db"
  qdrant:
    enabled: false

llm:
  openai:
    api_key: "${api_key}"
    model: "gpt-4o-mini"

mcp:
  enabled: true
  default_team_id: "default"
  default_owner_id: "local-user"

hooks:
  enabled: true

scheduler:
  enabled: true
  cleanup_interval: 1h
  access_flush_interval: 30s

heartbeat:
  enabled: true
  interval: 6h
YAML

    info "Config written to ${config_file}"
}

# ── 安装 AGENTS 指令源文件 / Install AGENTS source file ──
install_agents_source() {
    local src_url="https://raw.githubusercontent.com/${REPO}/main/integrations/codex/AGENTS.localmem.md"
    local dest="$INSTALL_DIR/codex-agents.md"

    info "Downloading AGENTS.localmem.md..."
    if ! curl -fsSL -o "$dest" "$src_url"; then
        # 回退：使用内嵌最小版本 / Fallback: embedded minimal version
        warn "Download failed, using embedded fallback"
        cat > "$dest" << 'FALLBACK'
<!-- LOCALMEM:BEGIN v1 -->
## Memory System (LocalMem)

You have access to a persistent cross-session memory system via MCP tools prefixed with `iclude_`.

### Retrieval Strategy (MUST follow)
1. **Session start** — Call `iclude_scan` with user's question BEFORE answering.
2. **Scan then Fetch** — Use `iclude_fetch` for items needing full content. Avoid `iclude_recall`.
3. **Mid-conversation** — Call `iclude_scan` again when user references unknown context.
4. **Timeline** — Use `iclude_timeline` for "what happened recently" questions.
5. **Deep reasoning** — Use `iclude_reflect` to synthesize multiple memories.

### Conversation Collection (SHOULD follow)
- After meaningful sessions, call `iclude_ingest_conversation`.
- Use `iclude_retain` to save individual important facts.
- Do NOT over-collect trivial Q&A.
<!-- LOCALMEM:END -->
FALLBACK
    fi
    info "AGENTS source installed to ${dest}"
}

# ── 注入 AGENTS.md（标记隔离）/ Inject into AGENTS.md with markers ──
inject_agents_md() {
    local codex_dir="$HOME/.codex"
    mkdir -p "$codex_dir"
    local agents_file="$codex_dir/AGENTS.md"
    local source_file="$INSTALL_DIR/codex-agents.md"
    local begin_marker="<!-- LOCALMEM:BEGIN"
    local end_marker="<!-- LOCALMEM:END -->"

    if [ ! -f "$source_file" ]; then
        warn "Source file ${source_file} not found, skipping AGENTS.md injection"
        return
    fi

    if [ -f "$agents_file" ]; then
        # 已有标记 → 删除旧区间 / Existing markers → remove old block
        if grep -q "$begin_marker" "$agents_file" 2>/dev/null; then
            # sed: 删除 BEGIN 行到 END 行之间的所有内容（含标记行）
            sed -i.bak "/$begin_marker/,/$end_marker/d" "$agents_file"
            info "Removed old LocalMem block from AGENTS.md"
        fi
    fi

    # 追加源文件内容 / Append source file content
    {
        echo ""
        cat "$source_file"
    } >> "$agents_file"

    # 清理多余空行 / Clean up trailing blank lines
    sed -i.bak -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$agents_file"
    rm -f "${agents_file}.bak"

    info "LocalMem instructions injected into ${agents_file}"
}

# ── 注入 developer_instructions / Inject developer_instructions into config.toml ──
inject_developer_instructions() {
    local codex_dir="$HOME/.codex"
    local config_file="$codex_dir/config.toml"
    local instruction='developer_instructions = "You have LocalMem memory tools (iclude_*). ALWAYS call iclude_scan at conversation start before answering. Use scan->fetch pattern to save tokens."'

    if [ ! -f "$config_file" ]; then
        return
    fi

    if grep -q "developer_instructions" "$config_file" 2>/dev/null; then
        if grep -q "iclude_scan" "$config_file" 2>/dev/null; then
            info "developer_instructions already contains LocalMem guidance, skipping"
            return
        fi
        warn "developer_instructions already set by user, skipping to avoid conflict"
        return
    fi

    # 在文件顶部插入（在 [mcp_servers] 之前） / Insert near top, before [mcp_servers]
    sed -i.bak "1i\\
${instruction}\\
" "$config_file"
    rm -f "${config_file}.bak"

    info "developer_instructions injected into ${config_file}"
}

# ── 配置 Codex CLI MCP / Configure Codex CLI MCP ──
configure_codex() {
    local codex_dir="$HOME/.codex"
    mkdir -p "$codex_dir"

    local config_file="$codex_dir/config.toml"

    if [ -f "$config_file" ] && grep -q "iclude" "$config_file" 2>/dev/null; then
        info "Codex CLI config already contains iclude, skipping"
        return
    fi

    if [ -f "$config_file" ]; then
        cp "$config_file" "${config_file}.bak"
        warn "Backed up existing config.toml to config.toml.bak"
        # 追加 iclude MCP server 配置到已有文件 / Append iclude MCP server to existing config
        cat >> "$config_file" << TOML

[mcp_servers.iclude]
command = "${BIN_DIR}/iclude-mcp"
args = ["--stdio", "--config", "${INSTALL_DIR}/config.yaml"]
startup_timeout_sec = 30
tool_timeout_sec = 60
enabled = true
TOML
    else
        cat > "$config_file" << TOML
# Codex CLI config — auto-generated by LocalMem install.sh

[mcp_servers.iclude]
command = "${BIN_DIR}/iclude-mcp"
args = ["--stdio", "--config", "${INSTALL_DIR}/config.yaml"]
startup_timeout_sec = 30
tool_timeout_sec = 60
enabled = true
TOML
    fi

    info "Codex CLI MCP config written to ${config_file}"
}

# ── 卸载 / Uninstall ──
uninstall() {
    info "Uninstalling LocalMem (Codex CLI integration)..."
    rm -rf "$INSTALL_DIR"
    for rc in "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.profile"; do
        if [ -f "$rc" ]; then
            sed -i.bak '/# LocalMem memory system/d;/.iclude\/bin/d' "$rc" 2>/dev/null || true
        fi
    done
    info "LocalMem uninstalled. Remove [mcp_servers.iclude] section from ~/.codex/config.toml manually if needed."
    exit 0
}

# ── 主流程 / Main ──
main() {
    if [ "${1:-}" = "--uninstall" ]; then
        uninstall
    fi

    echo ""
    echo "  LocalMem × Codex CLI Installer"
    echo "  ================================"
    echo ""

    detect_platform
    get_latest_version
    download_binaries
    add_to_path
    generate_config
    install_agents_source
    configure_codex
    inject_agents_md
    inject_developer_instructions

    echo ""
    info "Installation complete!"
    echo ""
    echo "  Restart Codex CLI to activate LocalMem memory system."
    echo "  Config: ${INSTALL_DIR}/config.yaml"
    echo "  Data:   ${INSTALL_DIR}/iclude.db"
    echo ""
}

main "$@"
