# LocalMem × Codex CLI 一键集成 (Windows) / One-click integration for OpenAI Codex CLI
# Usage: irm https://raw.githubusercontent.com/MemoryGet/LocalMem/main/integrations/codex/install.ps1 | iex

$ErrorActionPreference = "Stop"
$REPO = "MemoryGet/LocalMem"
$INSTALL_DIR = "$env:USERPROFILE\.iclude"
$BIN_DIR = "$INSTALL_DIR\bin"

function Info($msg)  { Write-Host "[INFO] $msg" -ForegroundColor Green }
function Warn($msg)  { Write-Host "[WARN] $msg" -ForegroundColor Yellow }
function Err($msg)   { Write-Host "[ERROR] $msg" -ForegroundColor Red; exit 1 }

Write-Host ""
Write-Host "  LocalMem x Codex CLI Installer"
Write-Host "  ================================"
Write-Host ""

# ── 检测架构 / Detect architecture ──
$ARCH = if ([Environment]::Is64BitOperatingSystem) {
    if ($env:PROCESSOR_ARCHITECTURE -eq "ARM64") { "arm64" } else { "amd64" }
} else { Err "32-bit systems not supported" }
Info "Platform: windows/$ARCH"

# ── 获取最新版本 / Get latest version ──
try {
    $release = Invoke-RestMethod "https://api.github.com/repos/$REPO/releases/latest"
    $VERSION = $release.tag_name
} catch {
    $VERSION = "latest"
    Warn "Could not detect latest release"
}
Info "Version: $VERSION"

# ── 下载二进制 / Download binaries ──
New-Item -ItemType Directory -Path $BIN_DIR -Force | Out-Null
$baseUrl = "https://github.com/$REPO/releases/download/$VERSION"

foreach ($bin in @("iclude-mcp", "iclude-cli")) {
    $url = "$baseUrl/$bin-windows-$ARCH.exe"
    $dest = "$BIN_DIR\$bin.exe"
    Info "Downloading $bin..."
    try {
        Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing
    } catch {
        Err "Failed to download $bin from $url"
    }
}
Info "Binaries installed to $BIN_DIR\"

# ── 加入 PATH / Add to PATH ──
$currentPath = [Environment]::GetEnvironmentVariable("PATH", "User")
if ($currentPath -notlike "*$BIN_DIR*") {
    [Environment]::SetEnvironmentVariable("PATH", "$BIN_DIR;$currentPath", "User")
    $env:PATH = "$BIN_DIR;$env:PATH"
    Info "Added $BIN_DIR to user PATH"
} else {
    Info "PATH already configured"
}

# ── 生成配置 / Generate config ──
$configFile = "$INSTALL_DIR\config.yaml"
if (!(Test-Path $configFile)) {
    $apiKey = Read-Host "Enter your OpenAI API Key (or press Enter to skip)"
    if ([string]::IsNullOrEmpty($apiKey)) {
        $apiKey = '${OPENAI_API_KEY}'
        Warn "No API key provided. Set OPENAI_API_KEY environment variable before use."
    }

    $dbPath = "$INSTALL_DIR\iclude.db" -replace '\\', '/'
    $configContent = @"
# LocalMem config - auto-generated by install.ps1
storage:
  sqlite:
    enabled: true
    path: "$dbPath"
  qdrant:
    enabled: false
llm:
  openai:
    api_key: "$apiKey"
    model: "gpt-4o-mini"
mcp:
  enabled: true
  default_team_id: "default"
  default_owner_id: "local-user"
hooks:
  enabled: true
scheduler:
  enabled: true
  cleanup_interval: 1h
  access_flush_interval: 30s
heartbeat:
  enabled: true
  interval: 6h
"@
    Set-Content -Path $configFile -Value $configContent -Encoding UTF8
    Info "Config written to $configFile"
} else {
    Warn "Config already exists, skipping"
}

# ── 安装 AGENTS 指令源文件 / Install AGENTS source file ──
$agentsSrc = "https://raw.githubusercontent.com/$REPO/main/integrations/codex/AGENTS.localmem.md"
$agentsDest = "$INSTALL_DIR\codex-agents.md"
Info "Downloading AGENTS.localmem.md..."
try {
    Invoke-WebRequest -Uri $agentsSrc -OutFile $agentsDest -UseBasicParsing
} catch {
    Warn "Download failed, using embedded fallback"
    $fallback = @"
<!-- LOCALMEM:BEGIN v1 -->
## Memory System (LocalMem)

You have access to a persistent cross-session memory system via MCP tools prefixed with ``iclude_``.

### Retrieval Strategy (MUST follow)
1. **Session start** — Call ``iclude_scan`` with user's question BEFORE answering.
2. **Scan then Fetch** — Use ``iclude_fetch`` for items needing full content. Avoid ``iclude_recall``.
3. **Mid-conversation** — Call ``iclude_scan`` again when user references unknown context.
4. **Timeline** — Use ``iclude_timeline`` for "what happened recently" questions.
5. **Deep reasoning** — Use ``iclude_reflect`` to synthesize multiple memories.

### Conversation Collection (SHOULD follow)
- After meaningful sessions, call ``iclude_ingest_conversation``.
- Use ``iclude_retain`` to save individual important facts.
- Do NOT over-collect trivial Q&A.
<!-- LOCALMEM:END -->
"@
    Set-Content -Path $agentsDest -Value $fallback -Encoding UTF8
}
Info "AGENTS source installed to $agentsDest"

# ── 注入 AGENTS.md（标记隔离）/ Inject into AGENTS.md with markers ──
$codexDir = "$env:USERPROFILE\.codex"
New-Item -ItemType Directory -Path $codexDir -Force | Out-Null
$agentsFile = "$codexDir\AGENTS.md"
$sourceContent = Get-Content -Path $agentsDest -Raw -ErrorAction SilentlyContinue

if ($sourceContent) {
    if (Test-Path $agentsFile) {
        $existing = Get-Content -Path $agentsFile -Raw
        if ($existing -match '(?s)<!-- LOCALMEM:BEGIN.*?<!-- LOCALMEM:END -->') {
            $existing = $existing -replace '(?s)\r?\n?<!-- LOCALMEM:BEGIN.*?<!-- LOCALMEM:END -->\r?\n?', ''
            Set-Content -Path $agentsFile -Value $existing.TrimEnd() -Encoding UTF8
            Info "Removed old LocalMem block from AGENTS.md"
        }
    }
    Add-Content -Path $agentsFile -Value ("`n" + $sourceContent) -Encoding UTF8
    Info "LocalMem instructions injected into $agentsFile"
}

# ── 注入 developer_instructions / Inject developer_instructions ──
# (handled after config.toml creation below)

# ── 配置 Codex CLI MCP / Configure Codex CLI MCP ──
New-Item -ItemType Directory -Path $codexDir -Force | Out-Null
$codexFile = "$codexDir\config.toml"

$codexMcpBin = "$BIN_DIR\iclude-mcp.exe" -replace '\\', '/'
$codexConfigPath = "$INSTALL_DIR\config.yaml" -replace '\\', '/'
$codexEntry = @"

[mcp_servers.iclude]
command = "$codexMcpBin"
args = ["--stdio", "--config", "$codexConfigPath"]
startup_timeout_sec = 30
tool_timeout_sec = 60
enabled = true
"@

if ((Test-Path $codexFile) -and (Get-Content $codexFile -Raw) -like "*iclude*") {
    Info "Codex CLI config already contains iclude, skipping"
} else {
    if (Test-Path $codexFile) {
        Copy-Item $codexFile "$codexFile.bak"
        Warn "Backed up existing config.toml"
        Add-Content -Path $codexFile -Value $codexEntry -Encoding UTF8
    } else {
        $codexHeader = "# Codex CLI config - auto-generated by LocalMem install.ps1`n"
        Set-Content -Path $codexFile -Value ($codexHeader + $codexEntry.TrimStart()) -Encoding UTF8
    }
    Info "Codex CLI MCP config written to $codexFile"
}

# ── 注入 developer_instructions 到 config.toml ──
if (Test-Path $codexFile) {
    $codexContent = Get-Content -Path $codexFile -Raw
    if ($codexContent -notmatch 'developer_instructions') {
        $devInstr = 'developer_instructions = "You have LocalMem memory tools (iclude_*). ALWAYS call iclude_scan at conversation start before answering. Use scan->fetch pattern to save tokens."'
        Set-Content -Path $codexFile -Value ($devInstr + "`n" + $codexContent) -Encoding UTF8
        Info "developer_instructions injected into $codexFile"
    } elseif ($codexContent -match 'iclude_scan') {
        Info "developer_instructions already contains LocalMem guidance, skipping"
    } else {
        Warn "developer_instructions already set by user, skipping to avoid conflict"
    }
}

Write-Host ""
Info "Installation complete!"
Write-Host ""
Write-Host "  Restart Codex CLI to activate LocalMem memory system."
Write-Host "  Config: $configFile"
Write-Host "  Data:   $INSTALL_DIR\iclude.db"
Write-Host ""
