# LocalMem × Codex CLI 一键集成 (Windows) / One-click integration for OpenAI Codex CLI
# Usage: irm https://raw.githubusercontent.com/MemoryGet/LocalMem/main/integrations/codex/install.ps1 | iex

$ErrorActionPreference = "Stop"
$REPO = "MemoryGet/LocalMem"
$INSTALL_DIR = "$env:USERPROFILE\.iclude"
$BIN_DIR = "$INSTALL_DIR\bin"

function Info($msg)  { Write-Host "[INFO] $msg" -ForegroundColor Green }
function Warn($msg)  { Write-Host "[WARN] $msg" -ForegroundColor Yellow }
function Err($msg)   { Write-Host "[ERROR] $msg" -ForegroundColor Red; exit 1 }

Write-Host ""
Write-Host "  LocalMem x Codex CLI Installer"
Write-Host "  ================================"
Write-Host ""

# ── 检测架构 / Detect architecture ──
$ARCH = if ([Environment]::Is64BitOperatingSystem) {
    if ($env:PROCESSOR_ARCHITECTURE -eq "ARM64") { "arm64" } else { "amd64" }
} else { Err "32-bit systems not supported" }
Info "Platform: windows/$ARCH"

# ── 获取最新版本 / Get latest version ──
try {
    $release = Invoke-RestMethod "https://api.github.com/repos/$REPO/releases/latest"
    $VERSION = $release.tag_name
} catch {
    $VERSION = "latest"
    Warn "Could not detect latest release"
}
Info "Version: $VERSION"

# ── 下载二进制 / Download binaries ──
New-Item -ItemType Directory -Path $BIN_DIR -Force | Out-Null
$baseUrl = "https://github.com/$REPO/releases/download/$VERSION"

foreach ($bin in @("iclude-mcp", "iclude-cli")) {
    $url = "$baseUrl/$bin-windows-$ARCH.exe"
    $dest = "$BIN_DIR\$bin.exe"
    Info "Downloading $bin..."
    try {
        Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing
    } catch {
        Err "Failed to download $bin from $url"
    }
}
Info "Binaries installed to $BIN_DIR\"

# ── 加入 PATH / Add to PATH ──
$currentPath = [Environment]::GetEnvironmentVariable("PATH", "User")
if ($currentPath -notlike "*$BIN_DIR*") {
    [Environment]::SetEnvironmentVariable("PATH", "$BIN_DIR;$currentPath", "User")
    $env:PATH = "$BIN_DIR;$env:PATH"
    Info "Added $BIN_DIR to user PATH"
} else {
    Info "PATH already configured"
}

# ── 生成配置 / Generate config ──
$configFile = "$INSTALL_DIR\config.yaml"
if (!(Test-Path $configFile)) {
    $apiKey = Read-Host "Enter your OpenAI API Key (or press Enter to skip)"
    if ([string]::IsNullOrEmpty($apiKey)) {
        $apiKey = '${OPENAI_API_KEY}'
        Warn "No API key provided. Set OPENAI_API_KEY environment variable before use."
    }

    $dbPath = "$INSTALL_DIR\iclude.db" -replace '\\', '/'
    $configContent = @"
# LocalMem config - auto-generated by install.ps1
storage:
  sqlite:
    enabled: true
    path: "$dbPath"
  qdrant:
    enabled: false
llm:
  openai:
    api_key: "$apiKey"
    model: "gpt-4o-mini"
mcp:
  enabled: true
  default_team_id: "default"
  default_owner_id: "local-user"
hooks:
  enabled: true
scheduler:
  enabled: true
  cleanup_interval: 1h
  access_flush_interval: 30s
heartbeat:
  enabled: true
  interval: 6h
"@
    Set-Content -Path $configFile -Value $configContent -Encoding UTF8
    Info "Config written to $configFile"
} else {
    Warn "Config already exists, skipping"
}

# ── 配置 Codex CLI MCP / Configure Codex CLI MCP ──
$codexDir = "$env:USERPROFILE\.codex"
New-Item -ItemType Directory -Path $codexDir -Force | Out-Null
$codexFile = "$codexDir\config.toml"

$codexMcpBin = "$BIN_DIR\iclude-mcp.exe" -replace '\\', '/'
$codexConfigPath = "$INSTALL_DIR\config.yaml" -replace '\\', '/'
$codexEntry = @"

[mcp_servers.iclude]
command = "$codexMcpBin"
args = ["--stdio", "--config", "$codexConfigPath"]
startup_timeout_sec = 30
tool_timeout_sec = 60
enabled = true
"@

if ((Test-Path $codexFile) -and (Get-Content $codexFile -Raw) -like "*iclude*") {
    Info "Codex CLI config already contains iclude, skipping"
} else {
    if (Test-Path $codexFile) {
        Copy-Item $codexFile "$codexFile.bak"
        Warn "Backed up existing config.toml"
        Add-Content -Path $codexFile -Value $codexEntry -Encoding UTF8
    } else {
        $codexHeader = "# Codex CLI config - auto-generated by LocalMem install.ps1`n"
        Set-Content -Path $codexFile -Value ($codexHeader + $codexEntry.TrimStart()) -Encoding UTF8
    }
    Info "Codex CLI MCP config written to $codexFile"
}

Write-Host ""
Info "Installation complete!"
Write-Host ""
Write-Host "  Restart Codex CLI to activate LocalMem memory system."
Write-Host "  Config: $configFile"
Write-Host "  Data:   $INSTALL_DIR\iclude.db"
Write-Host ""
