#!/bin/bash
set -euo pipefail

# LocalMem × Claude Code 一键集成 / One-click integration for Claude Code (Linux/macOS)
# Usage: curl -fsSL https://raw.githubusercontent.com/MemoryGet/LocalMem/main/integrations/claude/install.sh | bash

REPO="MemoryGet/LocalMem"
INSTALL_DIR="$HOME/.iclude"
BIN_DIR="$INSTALL_DIR/bin"

# ── 颜色输出 / Color output ──
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; exit 1; }

# ── 检测平台 / Detect platform ──
detect_platform() {
    OS=$(uname -s | tr '[:upper:]' '[:lower:]')
    ARCH=$(uname -m)
    case "$ARCH" in
        x86_64)  ARCH="amd64" ;;
        aarch64) ARCH="arm64" ;;
        arm64)   ARCH="arm64" ;;
        *)       error "Unsupported architecture: $ARCH" ;;
    esac
    case "$OS" in
        linux|darwin) ;;
        *)  error "Unsupported OS: $OS. Use install.ps1 for Windows." ;;
    esac
    info "Platform: ${OS}/${ARCH}"
}

# ── 获取最新版本 / Get latest release version ──
get_latest_version() {
    VERSION=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" 2>/dev/null \
        | grep '"tag_name"' | head -1 | sed -E 's/.*"([^"]+)".*/\1/' || true)
    if [ -z "$VERSION" ]; then
        VERSION="latest"
        warn "Could not detect latest release version"
    fi
    info "Version: ${VERSION}"
}

# ── 下载二进制 / Download binaries ──
download_binaries() {
    mkdir -p "$BIN_DIR"
    local base_url="https://github.com/${REPO}/releases/download/${VERSION}"

    for bin in iclude-mcp iclude-cli; do
        local url="${base_url}/${bin}-${OS}-${ARCH}"
        local dest="${BIN_DIR}/${bin}"
        info "Downloading ${bin}..."
        if ! curl -fsSL -o "$dest" "$url"; then
            error "Failed to download ${bin} from ${url}"
        fi
        chmod +x "$dest"
    done
    info "Binaries installed to ${BIN_DIR}/"
}

# ── 加入 PATH / Add to PATH ──
add_to_path() {
    local path_line="export PATH=\"${BIN_DIR}:\$PATH\""
    local added=false

    for rc in "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.profile"; do
        if [ -f "$rc" ]; then
            if ! grep -q ".iclude/bin" "$rc" 2>/dev/null; then
                echo "" >> "$rc"
                echo "# LocalMem memory system" >> "$rc"
                echo "$path_line" >> "$rc"
                added=true
            fi
        fi
    done

    export PATH="${BIN_DIR}:$PATH"

    if [ "$added" = true ]; then
        info "Added ${BIN_DIR} to PATH (restart shell or run: source ~/.bashrc)"
    else
        info "PATH already configured"
    fi
}

# ── 生成配置 / Generate config ──
generate_config() {
    local config_file="$INSTALL_DIR/config.yaml"

    if [ -f "$config_file" ]; then
        warn "Config already exists at ${config_file}, skipping"
        return
    fi

    local api_key=""
    if [ -t 0 ]; then
        echo ""
        echo -n "Enter your OpenAI API Key (or press Enter to skip): "
        read -r api_key
    fi

    if [ -z "$api_key" ]; then
        api_key='${OPENAI_API_KEY}'
        warn "No API key provided. Set OPENAI_API_KEY environment variable before use."
    fi

    cat > "$config_file" << YAML
# LocalMem config — auto-generated by install.sh
storage:
  sqlite:
    enabled: true
    path: "${INSTALL_DIR}/iclude.db"
  qdrant:
    enabled: false

llm:
  openai:
    api_key: "${api_key}"
    model: "gpt-4o-mini"

mcp:
  enabled: true
  default_team_id: "default"
  default_owner_id: "local-user"

hooks:
  enabled: true
  host_tool: "claude-code"
  capture_mode: "auto"

scheduler:
  enabled: true
  cleanup_interval: 1h
  access_flush_interval: 30s

heartbeat:
  enabled: true
  interval: 6h
YAML

    info "Config written to ${config_file}"
}

# ── 配置 Claude Code MCP / Configure Claude Code MCP ──
configure_claude() {
    local claude_dir="$HOME/.claude"
    mkdir -p "$claude_dir"

    local mcp_file="$claude_dir/.mcp.json"
    if [ -f "$mcp_file" ] && grep -q '"iclude"' "$mcp_file" 2>/dev/null; then
        info "Claude Code MCP config already contains iclude, skipping"
        return
    fi

    if [ -f "$mcp_file" ]; then
        cp "$mcp_file" "${mcp_file}.bak"
        warn "Backed up existing .mcp.json to .mcp.json.bak"
        # 合并：在现有 mcpServers 中追加 iclude / Merge: append iclude to existing mcpServers
        if command -v python3 &>/dev/null; then
            python3 -c "
import json, sys
with open('$mcp_file.bak') as f:
    data = json.load(f)
data.setdefault('mcpServers', {})['iclude'] = {
    'type': 'stdio',
    'command': '${BIN_DIR}/iclude-mcp',
    'args': ['--stdio', '--config', '${INSTALL_DIR}/config.yaml']
}
with open('$mcp_file', 'w') as f:
    json.dump(data, f, indent=2)
" && info "Merged iclude into existing ${mcp_file}" && return
            warn "Python3 merge failed, overwriting .mcp.json (backup saved)"
        fi
    fi

    cat > "$mcp_file" << JSON
{
  "mcpServers": {
    "iclude": {
      "type": "stdio",
      "command": "${BIN_DIR}/iclude-mcp",
      "args": ["--stdio", "--config", "${INSTALL_DIR}/config.yaml"]
    }
  }
}
JSON
    info "Claude Code MCP config written to ${mcp_file}"
}

# ── 配置 Claude Code Hooks / Configure Claude Code hooks in settings.local.json ──
configure_hooks() {
    local claude_dir="$HOME/.claude"
    mkdir -p "$claude_dir"
    local settings_file="$claude_dir/settings.local.json"

    if [ -f "$settings_file" ] && grep -q "iclude-cli" "$settings_file" 2>/dev/null; then
        info "Hooks already configured in settings.local.json, skipping"
        return
    fi

    local hooks_json='{
  "hooks": {
    "SessionStart": [
      {
        "type": "command",
        "command": "'"${BIN_DIR}"'/iclude-cli hook session-start",
        "timeout": 10000
      }
    ],
    "PostToolUse": [
      {
        "type": "command",
        "command": "'"${BIN_DIR}"'/iclude-cli hook capture",
        "timeout": 5000
      }
    ],
    "Stop": [
      {
        "type": "command",
        "command": "'"${BIN_DIR}"'/iclude-cli hook session-stop",
        "timeout": 12000
      }
    ]
  }
}'

    if [ -f "$settings_file" ]; then
        cp "$settings_file" "${settings_file}.bak"
        # 合并 hooks 到现有 settings / Merge hooks into existing settings
        if command -v python3 &>/dev/null; then
            python3 -c "
import json
with open('${settings_file}.bak') as f:
    data = json.load(f)
hooks = json.loads('''${hooks_json}''')
data.setdefault('hooks', {})
for event, handlers in hooks['hooks'].items():
    existing = data['hooks'].get(event, [])
    # 避免重复添加 / Avoid duplicates
    iclude_cmds = {h.get('command','') for h in existing if 'iclude-cli' in h.get('command','')}
    for h in handlers:
        if h['command'] not in iclude_cmds:
            existing.append(h)
    data['hooks'][event] = existing
with open('${settings_file}', 'w') as f:
    json.dump(data, f, indent=2)
" && info "Hooks merged into ${settings_file}" && return
            warn "Python3 merge failed, writing hooks separately"
        fi
    fi

    echo "${hooks_json}" > "${settings_file}.hooks.json"
    # 无 python3 且无现有文件时直接写入 / No python3 and no existing file: write directly
    if [ ! -f "$settings_file" ]; then
        echo "${hooks_json}" > "$settings_file"
        info "Hooks config written to ${settings_file}"
    else
        warn "Cannot merge hooks automatically (no python3). Manual merge needed from ${settings_file}.hooks.json"
    fi
}

# ── 卸载 / Uninstall ──
uninstall() {
    info "Uninstalling LocalMem (Claude Code integration)..."
    rm -rf "$INSTALL_DIR"
    for rc in "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.profile"; do
        if [ -f "$rc" ]; then
            sed -i.bak '/# LocalMem memory system/d;/.iclude\/bin/d' "$rc" 2>/dev/null || true
        fi
    done
    info "LocalMem uninstalled. Remove iclude entry from ~/.claude/.mcp.json manually if needed."
    exit 0
}

# ── 主流程 / Main ──
main() {
    if [ "${1:-}" = "--uninstall" ]; then
        uninstall
    fi

    echo ""
    echo "  LocalMem × Claude Code Installer"
    echo "  ================================"
    echo ""

    detect_platform
    get_latest_version
    download_binaries
    add_to_path
    generate_config
    configure_claude
    configure_hooks

    echo ""
    info "Installation complete!"
    echo ""
    echo "  Restart Claude Code to activate LocalMem memory system."
    echo "  Config: ${INSTALL_DIR}/config.yaml"
    echo "  Data:   ${INSTALL_DIR}/iclude.db"
    echo ""
}

main "$@"
